-- DEPRECATED — normal_rak_data is no longer used by the app.
--
-- Master Rak Normal SO (per-material rak upload for Normal SO, built in
-- 007_normal_rak_data.sql / 010_normal_rak_data_full_columns.sql) has been
-- reverted. For Normal SO, rak grouping during recount is derived from field
-- team entry history (so_entries), same pattern as before this feature
-- existed. warehouse_racks (see 00x_racks.sql) is still used, but only as a
-- rak-code suggestion list per warehouse, not as a material→rak mapping.
--
-- The normal_rak_data table itself is intentionally NOT dropped here — if it
-- was already created and populated in a live environment, dropping it is a
-- separate, deliberate cleanup step for whoever manages the DB (no app code
-- reads or writes it anymore, so leaving it in place is harmless, just
-- unused). Uncomment below to actually drop it once you've confirmed nothing
-- else depends on it.
--
-- drop table if exists normal_rak_data;
